//! Edwards25519 scalars and points, strictly decoded (ADR-011).
//!
//! The curve is the Ed25519 curve of RFC 8032, the one the
//! transparent sphere already signs on. Arithmetic comes from
//! curve25519-dalek, constant time over secret scalars; the
//! independent implementation of the vector generator re-derives the
//! same group from the specification. Two rules, applied everywhere:
//!
//! 1. Decoding is strict. A point decodes only if the encoding is
//!    canonical (recompressing the decoded point reproduces the
//!    exact bytes, which excludes the nineteen non-canonical
//!    y values), the point is not the identity and is not of small
//!    order. A scalar decodes only if the 32 bytes are a non-zero
//!    little-endian value below the group order.
//! 2. Secrets never print. Scalar debug output is redacted; point
//!    display is lowercase hex, the single textual form.

use core::fmt;

use curve25519_dalek::constants::ED25519_BASEPOINT_POINT;
use curve25519_dalek::edwards::{CompressedEdwardsY, EdwardsPoint};
use curve25519_dalek::scalar::Scalar as DalekScalar;
use curve25519_dalek::traits::IsIdentity;
use subtle::ConstantTimeEq;

use crate::error::VeilError;

/// A scalar of the prime order subgroup, below the group order l.
///
/// Values decoded from bytes, added or multiplied by this crate are
/// always canonical: the RFC 8032 clamping of a wallet seed exceeds
/// l and is reduced to its canonical residue at derivation time
/// (the seed module), so that every scalar that exists in this crate
/// has exactly one 32-byte encoding.
#[derive(Clone, Copy)]
pub struct Scalar(pub(crate) DalekScalar);

impl Scalar {
    /// Decodes a scalar from its canonical encoding.
    ///
    /// # Errors
    ///
    /// Returns [`VeilError::NonCanonicalScalar`] if the value is
    /// zero or at least the group order l.
    pub fn decode(bytes: &[u8; 32]) -> Result<Self, VeilError> {
        if *bytes == [0u8; 32] {
            // Zero is not a scalar of the protocol: no key, no
            // blinding, no ephemeral ever decodes to it.
            return Err(VeilError::NonCanonicalScalar(*bytes));
        }
        match DalekScalar::from_canonical_bytes(*bytes).into() {
            Some(s) => Ok(Self(s)),
            None => Err(VeilError::NonCanonicalScalar(*bytes)),
        }
    }

    /// The canonical 32-byte little-endian encoding.
    #[must_use]
    pub fn encode(&self) -> [u8; 32] {
        self.0.to_bytes()
    }

    /// The zero scalar. Internal arithmetic only: no decodable,
    /// derivable or blinding scalar of the protocol is ever zero.
    pub const ZERO: Scalar = Scalar(DalekScalar::ZERO);

    /// Constant-time equality of two scalars.
    #[must_use]
    pub fn ct_eq(&self, other: &Self) -> bool {
        self.0.ct_eq(&other.0).into()
    }
}

impl core::ops::Add for Scalar {
    type Output = Scalar;
    fn add(self, rhs: Scalar) -> Scalar {
        Scalar(self.0 + rhs.0)
    }
}

impl From<u64> for Scalar {
    /// The scalar of an atomic amount. Amounts are bounded by the
    /// supply cap, far below the group order: always canonical.
    fn from(amount: u64) -> Scalar {
        Scalar(DalekScalar::from(amount))
    }
}

impl core::ops::Mul for Scalar {
    type Output = Scalar;
    fn mul(self, rhs: Scalar) -> Scalar {
        Scalar(self.0 * rhs.0)
    }
}

impl core::ops::Neg for Scalar {
    type Output = Scalar;
    fn neg(self) -> Scalar {
        Scalar(-self.0)
    }
}

impl PartialEq for Scalar {
    fn eq(&self, other: &Self) -> bool {
        self.ct_eq(other)
    }
}

impl Eq for Scalar {}

impl fmt::Debug for Scalar {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        // A scalar can be a secret key, a blinding factor or an
        // ephemeral: it never enters logs or debug output.
        write!(f, "Scalar(REDACTED)")
    }
}

/// An Edwards25519 point of the prime-order subgroup.
///
/// The encoding is the RFC 8032 compressed form: the little-endian
/// y coordinate in the low 255 bits, the sign of x in bit 255.
/// Only points of the prime-order subgroup (the group generated by
/// the standard base point) decode: a torsion point or a point of
/// mixed order would open the torsion attack class on key images,
/// and a key, a one-time address, a commitment or a key image that
/// degenerates would break the private sphere invariants.
#[derive(Clone, Copy, PartialEq, Eq)]
pub struct Point(pub(crate) EdwardsPoint);

impl Point {
    /// Decodes a point from its compressed encoding.
    ///
    /// # Errors
    ///
    /// Returns [`VeilError::NonCanonicalPoint`] when the
    /// recompression differs from the input (including the case of
    /// an undecodable x), [`VeilError::IdentityPoint`] for the
    /// identity encoding and [`VeilError::OutsideSubgroup`] for a
    /// point outside the prime-order subgroup.
    pub fn decode(bytes: &[u8; 32]) -> Result<Self, VeilError> {
        let compressed = CompressedEdwardsY(*bytes);
        let Some(point) = compressed.decompress() else {
            // No x on the curve for this y: the bytes are not a
            // point encoding at all.
            return Err(VeilError::NonCanonicalPoint(*bytes));
        };
        if point.compress() != compressed {
            // The nineteen y values at or above the prime alias to a
            // different point; the encoding is not canonical.
            return Err(VeilError::NonCanonicalPoint(*bytes));
        }
        if point.is_identity() {
            return Err(VeilError::IdentityPoint(*bytes));
        }
        if !Self(point).is_in_prime_subgroup() {
            return Err(VeilError::OutsideSubgroup(*bytes));
        }
        Ok(Self(point))
    }

    /// The canonical compressed encoding.
    #[must_use]
    pub fn encode(&self) -> [u8; 32] {
        self.0.compress().0
    }

    /// The standard generator G of the prime order subgroup.
    #[must_use]
    pub const fn generator() -> Self {
        Self(ED25519_BASEPOINT_POINT)
    }

    /// Constant-time equality of the two encodings.
    #[must_use]
    pub fn ct_eq(&self, other: &Self) -> bool {
        self.encode().ct_eq(&other.encode()).into()
    }

    /// Whether the point belongs to the prime-order subgroup, the
    /// group generated by the standard base point: the torsion
    /// component of the point is zero (l P = identity).
    ///
    /// Every point this crate produces is in the subgroup (RFC 8032
    /// keys by clamping, Hp images by cofactor clearing, every
    /// derived point by construction); the check guards the decode
    /// path against torsion and mixed-order inputs.
    #[must_use]
    pub fn is_in_prime_subgroup(&self) -> bool {
        self.0.is_torsion_free()
    }
}

impl core::ops::Add for Point {
    type Output = Point;
    fn add(self, rhs: Point) -> Point {
        Point(self.0 + rhs.0)
    }
}

impl core::ops::Sub for Point {
    type Output = Point;
    fn sub(self, rhs: Point) -> Point {
        Point(self.0 - rhs.0)
    }
}

impl core::ops::Mul<&Scalar> for &Point {
    type Output = Point;
    fn mul(self, rhs: &Scalar) -> Point {
        Point(self.0 * rhs.0)
    }
}

impl core::ops::Mul<&Scalar> for Point {
    type Output = Point;
    fn mul(self, rhs: &Scalar) -> Point {
        Point(self.0 * rhs.0)
    }
}

impl core::ops::Mul<&Point> for &Scalar {
    type Output = Point;
    fn mul(self, rhs: &Point) -> Point {
        Point(self.0 * rhs.0)
    }
}

impl core::ops::Mul<&Point> for Scalar {
    type Output = Point;
    fn mul(self, rhs: &Point) -> Point {
        Point(self.0 * rhs.0)
    }
}

impl fmt::Debug for Point {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "Point({self})")
    }
}

impl fmt::Display for Point {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        for byte in self.encode() {
            write!(f, "{byte:02x}")?;
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const G_BYTES: [u8; 32] = [
        0x58, 0x66, 0x66, 0x66, 0x66, 0x66, 0x66, 0x66, 0x66, 0x66, 0x66, 0x66, 0x66, 0x66, 0x66,
        0x66, 0x66, 0x66, 0x66, 0x66, 0x66, 0x66, 0x66, 0x66, 0x66, 0x66, 0x66, 0x66, 0x66, 0x66,
        0x66, 0x66,
    ];

    #[test]
    fn the_generator_decodes_and_roundtrips() {
        // The base point encoding, from RFC 7748 and every Ed25519
        // implementation: 586666...6666.
        let g = Point::decode(&G_BYTES).expect("the generator decodes");
        assert_eq!(g, Point::generator());
        assert_eq!(g.encode(), G_BYTES);
    }

    #[test]
    fn scalar_roundtrip_and_rejections() {
        let mut one_bytes = [0u8; 32];
        one_bytes[0] = 1;
        let one = Scalar::decode(&one_bytes).expect("one decodes");
        assert_eq!(one.encode(), one_bytes);
        assert_eq!(
            Scalar::decode(&one.encode()).expect("roundtrip").encode(),
            one_bytes
        );

        // Zero is not a scalar of the protocol.
        assert_eq!(
            Scalar::decode(&[0u8; 32]),
            Err(VeilError::NonCanonicalScalar([0u8; 32]))
        );

        // l itself is one above the last canonical value.
        let l_bytes: [u8; 32] = [
            0xed, 0xd3, 0xf5, 0x5c, 0x1a, 0x63, 0x12, 0x58, 0xd6, 0x9c, 0xf7, 0xa2, 0xde, 0xf9,
            0xde, 0x14, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00, 0x00, 0x10,
        ];
        assert_eq!(
            Scalar::decode(&l_bytes),
            Err(VeilError::NonCanonicalScalar(l_bytes))
        );
    }

    #[test]
    fn the_identity_is_refused() {
        // y = 1, sign 0: the identity.
        let mut identity = [0u8; 32];
        identity[0] = 1;
        assert_eq!(
            Point::decode(&identity),
            Err(VeilError::IdentityPoint(identity))
        );
    }

    #[test]
    fn small_order_points_are_refused() {
        // The order 2 point (0, -1): y = p - 1 = 2^255 - 20, sign of
        // the zero x at 0. Little-endian: ec ff ff ... ff 7f.
        let mut torsion = [0xffu8; 32];
        torsion[0] = 0xec;
        torsion[31] = 0x7f;
        assert_eq!(
            Point::decode(&torsion),
            Err(VeilError::OutsideSubgroup(torsion))
        );
    }

    #[test]
    fn mixed_order_points_are_refused() {
        // A point of order 8l: a valid prime-order point plus a
        // torsion point. Canonical encoding, not small order, and
        // still refused: l P is a nonzero torsion point.
        let g = Point::generator();
        let mut torsion_bytes = [0xffu8; 32];
        torsion_bytes[0] = 0xec;
        torsion_bytes[31] = 0x7f;
        let torsion = CompressedEdwardsY(torsion_bytes)
            .decompress()
            .expect("the order 2 point decompresses");
        let mixed = g.0 + torsion;
        let encoded = mixed.compress().0;
        assert_eq!(
            Point::decode(&encoded),
            Err(VeilError::OutsideSubgroup(encoded))
        );
    }

    #[test]
    fn generator_and_derived_points_are_in_the_subgroup() {
        let g = Point::generator();
        assert!(g.is_in_prime_subgroup());
        // Every small multiple of the generator is in the subgroup.
        for k in 1u8..=8 {
            let mut k_bytes = [0u8; 32];
            k_bytes[0] = k;
            let scalar = Scalar::decode(&k_bytes).expect("canonical");
            let point = &Point::generator() * &scalar;
            assert!(point.is_in_prime_subgroup());
            assert!(Point::decode(&point.encode()).is_ok());
        }
    }

    #[test]
    fn non_canonical_y_is_refused() {
        // The nineteen y values at or above p alias to another point:
        // recompression differs, decoding refuses. y = 2^255 - 1 is
        // the largest: little-endian ff ff ... ff 7f, sign at 0.
        let mut forged = [0xffu8; 32];
        forged[31] = 0x7f;
        assert_eq!(
            Point::decode(&forged),
            Err(VeilError::NonCanonicalPoint(forged))
        );
    }

    #[test]
    fn scalar_arithmetic_is_canonical_and_closed() {
        // (s + t) encodes below l for random canonical values: the
        // crate never produces a non-canonical scalar. Both top
        // bytes stay below 0x10, hence below the group order.
        let s_bytes: [u8; 32] = [
            0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e,
            0x0f, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1a, 0x1b, 0x1c,
            0x1d, 0x1e, 0x1f, 0x0f,
        ];
        let t_bytes: [u8; 32] = [
            0x30, 0x2e, 0x2c, 0x2a, 0x28, 0x26, 0x24, 0x22, 0x20, 0x1e, 0x1c, 0x1a, 0x18, 0x16,
            0x14, 0x12, 0x10, 0x0e, 0x0c, 0x0a, 0x08, 0x06, 0x04, 0x02, 0x01, 0x03, 0x05, 0x07,
            0x09, 0x0b, 0x0d, 0x01,
        ];
        let s = Scalar::decode(&s_bytes).expect("canonical");
        let t = Scalar::decode(&t_bytes).expect("canonical");
        let sum = s + t;
        assert_eq!(
            Scalar::decode(&sum.encode())
                .expect("sum is canonical")
                .encode(),
            sum.encode()
        );
        // Distributivity on the curve: (s + t) G = sG + tG.
        let left = &Point::generator() * &sum;
        let right = &Point::generator() * &s + &Point::generator() * &t;
        assert!(left.ct_eq(&right));
    }

    #[test]
    fn secrets_are_redacted_in_debug() {
        let mut one_bytes = [0u8; 32];
        one_bytes[0] = 1;
        let s = Scalar::decode(&one_bytes).expect("canonical");
        let formatted = format!("{s:?}");
        assert!(formatted.contains("REDACTED"));
        assert!(!formatted.contains("0100"));
    }
}
